### ISSUE TITLE
SN76489 Alt-Write is 6 bits ?

### ISSUE THREAD

**Issue by paulscottrobson** [pweingar/F256Manual#1]
In the table in 8.2.1 and the text in 8.2.2 for the SN76489 PSG when writing the second half of the tone data (e.g. with the MSB = 0) it refers to the "7 bits of the data" ; in the 76489 Applications manual bit 6 is marked as not used e.g. 0 X D D D D D D D

**Comment by pweingar** [comment]
Should be fixed now
