### ISSUE TITLE
VKY_BRDR_HORI and VKY_BRDR_VERT have their address swapped.

### ISSUE THREAD

**Issue by dillof** [pweingar/F256Manual#22]
The Example Changing Border with the Line contains the following definitions:

VKY_BRDR_VERT = $D008  ; Vicky Border vertical thickness in pixels
VKY_BRDR_HORI = $D009  ; Vicky Border Horizontal Thickness in pixels

In Table 7.2: the registers are listed in reserved order:

0xD008 BRDR_WIDTH 
0xD009 BRDR_HEIGHT

I've just confirmed on real hardware, the table is correct.

Generally, the register names in tables and examples often do not agree. Since I'm trying to create a file with all register definitions, which should be considered canonical?

thanks for the great reference manual,
Dillo

**Comment by pweingar** [comment]
Should be fixed now. Thanks!
