### ISSUE TITLE
Several errors in section 18, IEC Serial Port

### ISSUE THREAD

**Issue by OldBaldGeek** [pweingar/F256Manual#23]
1) Table 18.1 puts the IEC_O register at DC01. The source code and my debugger show it at D681, just above IEC_I. (DC01 is a VIA register)

2) Table 18.1 shows ATN_i as bit2, and ATN_o as bit4. The source code and my debugger indicate that both should be bit4

**Comment by pweingar** [comment]
Should be corrected now. Please let me know if it looks right.

**Comment by OldBaldGeek** [comment]
Change verified in pdf dated 13/12/2023
