### ISSUE TITLE
Error in section 17, System Control Registers

### ISSUE THREAD

**Issue by OldBaldGeek** [pweingar/F256Manual#24]
1) Table 17.1 shows reading D6A0 not to return the four LED bits states Tests on my F256 indicate that the LED bits ARE readable, which makes it much easier for code to manipulate one bit without affecting the others. I don't know whether this applies to the BUZZ bit

2) Table 17.1 has bits L1_MN and L0_MN. The text says that ZERO is the manual state. Experiment shows ONE is the manual state (which matches "MN" as a mnemonic for "manual)

**Comment by pweingar** [comment]
I'm not able to independently verify the L0_MN and L1_MN sense on my machine (can't see the LEDs), but I'll take your word for it. I did some tests on $D6A0, and it looks like the lower five bits are R/W. So I've updated the text and table accordingly.

Thanks!

**Comment by OldBaldGeek** [comment]
Change verified in pdf dated 13/12/2023
