### ISSUE TITLE
Incorrect Addresses

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#25]
https://github.com/pweingar/F256Manual/blob/1fd06eea3b128529f794302475c11f8166b79404/tex/vicky_misc.tex#L123
Should be $D66C.

https://github.com/pweingar/F256Manual/blob/1fd06eea3b128529f794302475c11f8166b79404/tex/vicky_misc.tex#L124
Should be $D66D.

**Comment by pweingar** [comment]
Should be corrected now. I wonder where that error came from, as it's correct in other places.
