### ISSUE TITLE
SID Description

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#26]
https://github.com/pweingar/F256Manual/blob/1fd06eea3b128529f794302475c11f8166b79404/tex/sysctrl.tex#L30C84-L30C84

SID only has 3 voices so the end of the paragraph should be "independent 3 voice channels in stereo or as a monaural 6 voice channels".

**Comment by pweingar** [comment]
Thanks! I must have had PSG on the brain at the time.

**Comment by pweingar** [comment]
Should be corrected now.
