### ISSUE TITLE
sprite example typo + suggestions

### ISSUE THREAD

**Issue by Mu0n** [pweingar/F256Manual#27]
Referring to pages 35 through 38

Typo: the line that says:
cmp #16 
should instead read:
cpx #16 (or cpx #$10, but we're looping across the x register here)
(credits to beethead for finding that one)

perhaps it would be a good idea to include some definitions, which are made in earlier examples before that point in the manual, but not redefined here:
VKY_GR_CLUT_0 = $D000

and I suspect you don't select zero page addresses for the 4 pointers you're using in your example for fear of having them fail in the future if they're sollicited by something, but these have worked for me as I rebuilt your example:
ptr_dst = $50
ptr_src = $52

I'll put a compileable copy of your example in my repo here shortly:
https://github.com/Mu0n/F256KsimpleASMdoodles

**Comment by pweingar** [comment]
I've updated the example. Check it out and see if it looks right. I've added some of the definitions you pointed out. The reason they were missing is that they are defined elsewhere in the actual project file (in the `examples/ex_sprites` directory).

**Comment by Mu0n** [comment]
Looks good!
