### ISSUE TITLE
C256jrManual/examples/common/f256_irq.asm

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#4]
The file contains the wrong addresses for the interrupt masks.
They should be `INT_MASK_0 = $D66C` and `INT_MASK_1 = $D66D`.

**Comment by pweingar** [comment]
What is your source for that? I was working off of Stefany's original user manual which has $D666 and $D667.

**Comment by noyen1973** [comment]
It's from a kernel listing I received from Stefany.  Plus my revision B IRQ handler finally works when booting in RAM mode.

**Comment by pweingar** [comment]
Thanks. I'll double-check with Stefany. I think the registers can repeat within their blocks so that $D666 is the same as $D66C, which may explain the difference. But I'll see what she says.

**Comment by pweingar** [comment]
I've confirmed with Stefany that you have the right addresses and have corrected the text. Thanks!
