### ISSUE TITLE
Wrong operand value

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#5]
https://github.com/pweingar/C256jrManual/blob/e61bedbe1799236e1c97db66188e1e995bbfd7ed/examples/ex_bitmaps/bitmaps.asm#L95

Shouldn't the operand be #$40 as per Table 4.3 in the manual? Tile Map Layer 0 has a code value of 4.

**Comment by pweingar** [comment]
Yes. That's something left over from and earlier version of the layers registers.

**Comment by pweingar** [comment]
Should be corrected now in both the ASM file and the manual itself (that portion is shown a bit before the bitmaps section).
