### ISSUE TITLE
Page 105, Table 20.4: I/O Page 0 Addresses SID Right

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#6]
Typo in the end address.

**Comment by pweingar** [comment]
Thanks! I'm glad you're looking over the manual in such detail.

**Comment by noyen1973** [comment]
It's the reference manual so I keep digging into it as I traverse the Jr world.  Graphics is next on my tour.
You've done a fantastic job for the amount of work that's been completed.  If it were me, I'd have a boo boos on every page.
