### ISSUE TITLE
Tile Size

### ISSUE THREAD

**Issue by noyen1973** [pweingar/F256Manual#9]
https://github.com/pweingar/C256jrManual/blob/64d566e4f53e3f5c8ff1fb139562f8424dcc1f75/tex/tiles.tex#L54

It's backwards, 0=16x16 tiles and 1=8x8 tiles

It's correct in the example,https://github.com/pweingar/C256jrManual/blob/64d566e4f53e3f5c8ff1fb139562f8424dcc1f75/examples/ex_tiles8/tiles8.asm#L116

**Comment by pweingar** [comment]
I've corrected the entry. Although the commit has some other stuff in it too.
